name: dart_practice
description: A sample Dart web application.
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  path: ^1.8.0
  http: ^1.1.0    # Use the latest compatible version of http for Dart 3.x

dev_dependencies:
  build_runner: ^2.4.0         # For building and code generation
  build_web_compilers: ^4.0.4  # For compiling Dart to JavaScript for the web
  webdev: ^2.8.0               # For serving the web app locally
  lints: ^2.0.0
  test: ^1.21.0
