name: dart_practice
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2  # Make sure this matches your Dart SDK version

dependencies:
  path: ^1.8.0
  http: ^1.1.0   # Updated version of http to be compatible with Dart 3.x
  html: ^0.15.0   # For manipulating HTML in the browser


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
